Reach milestone 2 & 3. HTML + CSS
KostyanWest/Alias_game pull request #2
Opened 2022-05-07 19:15 UTC by KostyanWest

Добавлены основные страницы приложения. Экран промежуточных результатов будет добавлен в следующей лабе, но выглядеть он будет аналогично существующим.

Управляюие элементы пока ни на что не влияют. Единственный рабочий функционал: переключение между станицами через панель навигации и кнопка смены темы (в верхнем правом углу).

Известные баги:
* при фокусе текстбокса на смартфоне появляется виртуальная клавиатура, из-за чего меняется viewport и сайт сжимается (может просто забить на это?).

Проверено в браузерах: Chrome, Edge и Chrome Android.

2022-05-14 19:10 UTC, Nastik1811 requested changes

2022-05-14 19:10 UTC, nastik1811 commented on styles/common.css
> +    display: none !important;
why important?

2022-05-14 19:10 UTC, nastik1811 commented on styles/page.css
> +    margin-right: -5rem;
why do you need negative margin?

2022-05-14 19:10 UTC, Nastik1811 commented on styles/common.css
> +    min-height: 100vh;
don't use `100vh`

2022-05-15 07:53 UTC, KostyanWest commented on styles/common.css
> +    display: none !important;
Чтобы не следить, находится ли класс `hidden` в конце цепочки. Если добавлен этот класс, значит объект должен быть скрыт. Этот класс в основном через JS добавляется.

2022-05-15 07:53 UTC, KostyanWest commented on styles/page.css
> +    margin-right: -5rem;
При отрицательном отступе страница накладывается на соседний элемент, и получается анимация исчезновения. У обычного `page` отступы нулевые.

2022-05-15 07:53 UTC, KostyanWest commented on styles/common.css
> +    min-height: 100vh;
А как тогда растянуть сайт на весь экран, даже если содержимое помещается в меньшем размере?

2022-05-18 07:54 UTC, nastik1811 commented on styles/common.css
> +    min-height: 100vh;
Вы можете погуглить или спросить у одногруппников

2022-05-24 12:06 UTC, KostyanWest commented on styles/common.css
> +    min-height: 100vh;
Я заменил `vh` на проценты. Что в целом по 3-й лабе? Можно сдавать уже 4-ю?

2022-05-25 12:18 UTC, Nastik1811 approved these changes

2022-05-26 00:35 UTC, merged